create profile PF_USER
limit password_life_time 365
password_reuse_time unlimited
failed_login_attempts 5
idle_time 60
sessions_per_user 3;

create profile PF_MODERATOR
limit password_life_time 90
password_reuse_time unlimited
failed_login_attempts 3
idle_time 20
sessions_per_user 1;

CREATE ROLE RL_USER;

GRANT EXECUTE ON USER_PACKAGE TO RL_USER;
GRANT EXECUTE ON cursor_Types TO RL_USER;

CREATE USER Reader IDENTIFIED BY 1122
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE PF_USER;

GRANT RL_USER TO Reader;

GRANT CREATE SESSION TO Reader;
GRANT CREATE SESSION TO RL_USER;
GRANT SELECT ON BOOK_STATUS TO RL_USER;

GRANT EXECUTE on USER_PACKAGE TO READER;

CREATE PUBLIC SYNONYM USER_PACKAGE FOR BOOKSSYS.USER_PACKAGE;
CREATE PUBLIC SYNONYM CURSOR_TYPES FOR BOOKSSYS.CURSOR_TYPES;
CREATE PUBLIC SYNONYM PGK_BOOK FOR BOOKSSYS.PKG_BOOK;
CREATE PUBLIC SYNONYM PKG_USER FOR BOOKSSYS.PKG_USER;



CREATE ROLE RL_Moderator;
GRANT RL_USER to RL_Moderator;
GRANT CREATE SESSION to RL_Moderator;
GRANT CREATE SESSION to Moderator;

GRANT EXECUTE ON PKG_BOOK to RL_Moderator;
GRANT EXECUTE ON PKG_USER to RL_Moderator;

CREATE USER Moderator IDENTIFIED BY 112211
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE PF_MODERATOR