CREATE VIEW FULL_BOOK_INFORMATION AS
SELECT *
FROM BOOK;


create OR REPLACE TRIGGER AVG_BOOK AFTER INSERT OR UPDATE or DELETE ON RATE FOR EACH ROW
    BEGIN
        IF :new.BOOK_ID IS NOT NULL then
        PKG_BOOK.COMPUTE_BOOK_AVG(:new.BOOK_ID);
        END IF;
        IF :old.BOOK_ID IS NOT NULL then
        PKG_BOOK.COMPUTE_BOOK_AVG(:old.BOOK_ID);
        END IF;
    END;

DROP TRIGGER AVG_BOOK;